@full
Feature: Zera o banco de dados
	
	@javascript
	Scenario: Teste completo
		
		# RESET
		Given I am on "/reset" visit
		Then I should see "OK"
		# END RESET

		# INDEX
		Given I am on "/" visit
		Then I should see "Login"
		Then I should see "Cadastro"
		# END INDEX

		# REGISTER
		When I follow "Cadastro"
		When I register user
		Then I should see "Cadastrado! Acesso liberado."
		When I follow "Cadastre-se"
		When I register user
		Then I should see "Usuário já cadastrado no sistema."
		# END REGISTER

		# LOGIN
		When I follow "Login"
		When I login
		Then I should be on "/app"
		Then I should see "Tester"
		Then I should see "Sair"

		When I follow "Lançamentos"
		Then I should be on "/app/releases"
		Then I should see "Adicionar"
		Then I should see "Abertas"
		Then I should see "Todas"
		Then I should see "Sem registros."

		When I follow "Todas"
		Then I should be on "/app/releases/i/all"
		Then I should see "Sem registros."

		When I follow "Abertas"
		Then I should be on "/app/releases"
		Then I should see "Sem registros."

		When I follow "Pessoas"
		Then I should be on "/app/peoples"
		Then I should see "Adicionar"
		Then I should see "Sem registros."

		When I follow "Categorias"
		Then I should be on "/app/categories"
		Then I should see "Adicionar"
		Then I should see "Sem registros."

		When I follow "Usuários"
		Then I should be on "/app/users"
		Then I should see "test@hmgestor.com"

		When I follow "Extrato"
		Then I should be on "/app/extract"
		Then I should see "Sem registros."

		When I follow "Logs"
		Then I should be on "/app/logs"
		Then I should see "Conectou-se"
		Then I should see "Tester"

		When I follow "Me"
		Then I should be on "/app/me"
		Then I should see "Baixar backup"
		Then I should see "Apagar minha conta"
		# END LOGIN
		
		# CATEGORIES
		When I follow "Categorias"
		Then I should be on "/app/categories"
		Then I should see "Adicionar"
		Then I should see "Nome"
		Then I should see "Sem registros."
		When I add category "Categoria 001"
		Then I should be on "/app/categories"
		Then I should see "Sucesso!"
		Then I should see "Categoria 001"
		When I follow "Logs"
		Then I should be on "/app/logs"
		Then I should see "Criou a categotia 'Categoria 001'."
		When I add category "Categoria 001"
		Then I should be on "/app/categories/form"
		Then I should see "Name must be unique"
		# END CATEGORIES
		
		# PEOPLES
		When I follow "Pessoas"
		Then I should be on "/app/peoples"
		Then I should see "Adicionar"
		Then I should see "Nome"
		Then I should see "Sem registros."
		When I add the person "Pessoa 001"
		Then I should be on "/app/peoples"
		Then I should see "Sucesso!"
		Then I should see "Pessoa 001"
		When I follow "Logs"
		Then I should be on "/app/logs"
		Then I should see "Adicionou 'Pessoa 001' em pessoas."
		When I add the person "Pessoa 001"
		Then I should be on "/app/peoples/form"
		Then I should see "Name must be unique"
		# END PEOPLES
		
		# RELEASES
		When I follow "Lançamentos"
		Then I should see "Adicionar"
		Then I should see "Abertas"
		Then I should see "Todas"
		Then I should see "Sem registros."

		When I follow "Adicionar"
		Then I should be on "/app/releases/form"
		Then I should see "Salvar"
		When I select "Pessoa 001" from "people_id"
		When I select "Categoria 001" from "category_id"
		Given When I fill in "value" with "1000,00"
		Given When I fill in "description" with "Receita de R$ 1.000,00 em 1x"
		Given I press "Salvar" button
		Then I should be on "/app/releases"
		Then I should see "Sucesso!"
		Then I should see "Pessoa 001"
		Then I should see "Categoria 001"
		Then I should see "1/1"
		Then I should see "1.000,00"
		Then I should see "Receita de R$ 1.000,00 em 1x"

		When I follow "Adicionar"
		Then I should be on "/app/releases/form"
		Then I should see "Salvar"
		When I select "Despesa" from "natureza"
		When I select "Pessoa 001" from "people_id"
		When I select "Categoria 001" from "category_id"
		Given When I fill in "quantity" with "2"
		Given When I fill in "value" with "100,00"
		Given When I fill in "description" with "Receita de R$ 100,00 em 2x"
		Given I press "Salvar" button
		Then I should be on "/app/releases"
		Then I should see "Sucesso!"
		Then I should see "Pessoa 001"
		Then I should see "Categoria 001"
		Then I should see "1/2"
		Then I should see "2/2"
		Then I should see "50,00"
		Then I should see "Receita de R$ 100,00 em 2x"

		When I follow "Adicionar"
		Then I should be on "/app/releases/form"
		Then I should see "Salvar"
		When I select "Despesa" from "natureza"
		When I select "Pessoa 001" from "people_id"
		When I select "Categoria 001" from "category_id"
		Given When I fill in "quantity" with "3"
		Given When I fill in "value" with "500,00"
		Given When I fill in "description" with "Receita de R$ 500,00 em 3x"
		Given I press "Salvar" button
		Then I should be on "/app/releases"
		Then I should see "Sucesso!"
		Then I should see "Pessoa 001"
		Then I should see "Categoria 001"
		Then I should see "1/3"
		Then I should see "2/3"
		Then I should see "3/3"
		Then I should see "166,67"
		Then I should see "166,66"
		Then I should see "Receita de R$ 500,00 em 3x"

		Then I follow "Logs"
		Then I should be on "/app/logs"
		Then I should see "Emissão receita nº 1/1 'Pessoa 001' R$ 1.000,00"
		Then I should see "Emissão despesa nº 1/2 'Pessoa 001' R$ 50,00"
		Then I should see "Emissão despesa nº 2/2 'Pessoa 001' R$ 50,00"
		Then I should see "Emissão despesa nº 1/3 'Pessoa 001' R$ 166,67"
		Then I should see "Emissão despesa nº 2/3 'Pessoa 001' R$ 166,67"
		Then I should see "Emissão despesa nº 3/3 'Pessoa 001' R$ 166,66"
		Then I should not see "Restaurar"

		When I follow "Lançamentos"
		Then I follow "1/1"
		Then I should see "Extrato de lançamento"
		Then I should see "Emissão"
		Then I should see "Lançamento nº 1/1"
		Then I should see "Liquidar"
		Then I should see "Editar"
		Then I should see "Apagar este lançamento"
		Then I should see "Apagar todos os lançamentos deste documento"
		Then I should see "1.000,00"
		Then I follow "Liquidar"
		Then I should see "Lista de ações da parcela"
		Then the "value" field should contain "1000"
		Then I should see "Liquidar"
		Given When I fill in "value" with "350"
		Given I press "Liquidar" button
		Then I should see "Sucesso!"
		Then I should see "Recebimento"
		Then I should see "350,00"
		Then I should not see "Editar"

		When I follow "Lançamentos"
		Then I follow "1/1"
		Then I follow "Liquidar"
		Then the "value" field should contain "650"
		Given When I fill in "value" with "712"
		Given I press "Liquidar" button
		Then I should see "Sucesso!"
		Then I should see "Emissão"
		Then I should see "1.000,00"
		Then I should see "Recebimento"
		Then I should see "350,00"
		Then I should see "Encargos"
		Then I should see "62,00"
		Then I should see "712,00"

		Then I follow "Logs"
		Then I should be on "/app/logs"		
		Then I should see "Recebimento receita nº 1/1 'Pessoa 001' R$ 350,00"
		Then I should see "Recebimento receita nº 1/1 'Pessoa 001' R$ 712,00"
		Then I should see "Encargos receita nº 1/1 'Pessoa 001' R$ 62,00"

		When I follow "Lançamentos"
		Then I follow "Todas"
		Then I follow "1/1"
		Then I follow "Desfazer"
		Then I should see "Sucesso!"
		Then I should not see "Encargos"
		Then I should not see "62,00"
		Then I should not see "712,00"
		Then I should see "Recebimento"
		Then I should see "350,00"

		When I follow "Lançamentos"
		Then I follow "1/1"
		Then I follow "Liquidar"
		Then the "value" field should contain "650"
		Given When I fill in "value" with "585"
		Then I check with click on "desconto"
		Given I press "Liquidar" button
		Then I should see "Sucesso!"
		Then I should see "Emissão"
		Then I should see "1.000,00"
		Then I should see "Recebimento"
		Then I should see "350,00"
		Then I should see "Desconto"
		Then I should see "65,00"
		Then I should see "585,00"
		Then I follow "Lançamentos"
		Then I should not see "1/1"
		Then I follow "Todas"
		Then I should see "1/1"
		Then I should see "Pago"
		Then I should see "935,00"

		Then I follow "Logs"
		Then I should be on "/app/logs"		
		Then I should see "Recebimento receita nº 1/1 'Pessoa 001' R$ 585,00"
		Then I should see "Desconto receita nº 1/1 'Pessoa 001' R$ 65,00"

		When I follow "Lançamentos"
		Then I follow "Todas"
		Then I follow "1/1"
		Then I follow "Desfazer"
		Then I should see "Sucesso!"
		Then I should not see "Desconto"
		Then I should not see "65,00"
		Then I should not see "585,00"
		Then I should see "Recebimento"
		Then I should see "350,00"
		Then I follow "Lançamentos"
		Then I should see "650,00"

		When I follow "Lançamentos"
		Then I follow "1/1"
		Then I follow "Apagar este lançamento"
		Then I should see "O lançamento '1/1' foi movimentado."
		Then I follow "O lançamento '1/1' foi movimentado."
		Then I should not see "O lançamento '1/1' foi movimentado."
		Then I follow "Apagar todos os lançamentos deste documento"
		Then I should see "O lançamento '1/1' foi movimentado."
		Then I follow "O lançamento '1/1' foi movimentado."
		Then I should not see "O lançamento '1/1' foi movimentado."		

		When I follow "Lançamentos"
		Then I follow "1/1"
		Then I follow "Desfazer"
		Then I should see "Sucesso!"
		Then I should not see "Recebimento"
		Then I should not see "350,00"
		Then I should see "Editar"
		Then I follow "Lançamentos"
		Then I should see "1/1"
		Then I should see "1.000,00"

		Then I follow "Pessoas"
		Then I should be on "/app/peoples"
		Then I follow "delete-person-1"
		Then I should see "Este registro está em uso no sistema."

		Then I follow "Categorias"
		Then I should be on "/app/categories"
		Then I follow "delete-category-1"
		Then I should see "Este registro está em uso no sistema."

		When I follow "Lançamentos"
		Then I follow "1/1"
		Then I follow "Apagar este lançamento"
		Then I should see "Sucesso!"
		Then I should not see "1/1"
		Then I follow "Todas"
		Then I should not see "1/1"
		Then I should see "1/2"
		Then I should see "2/2"
		Then I should see "1/3"
		Then I should see "2/3"
		Then I should see "3/3"