#!/bin/bash

DB_LOCAL="euconomista"
DB_USER='root'
DB_PASS='123'
DOMAIN='gilglecio@gilglecio.com.br'

FOLDER="backups"

if [ -z "$1" ] 
	then
	echo -ne "Gerando arquivo remoto...\n"
	file=$(ssh $DOMAIN "./backup.sh")
else
	file=$1
fi

mkdir -p "./$FOLDER"

echo -ne "Baixando arquivo remoto...\n"
scp $DOMAIN:/home/gilglecio/bkp_mysql/"$file" ./$FOLDER

unziped=$(echo $file | sed "s/.gz//g")

echo -ne "Descompactando banco de dados...\n"
gzip -d "./$FOLDER/$file"

echo -ne "Excluído e criando base de dados local...\n"
mysql -u$DB_USER -p$DB_PASS -e "drop database $DB_LOCAL; create database $DB_LOCAL"

echo -ne "Importando banco de dados...\n"
mysql -u$DB_USER -p$DB_PASS $DB_LOCAL < "./$FOLDER/$unziped"

echo "Processo finalizado."