version: '3'

services:
  api:
    build: .
    container_name: euconomista_api
    working_dir: /var/www
    depends_on:
      - mysql
    volumes:
      - .:/var/www
    ports:
      - "3000:80"
    network_mode: euconomista

  mysql:
    image: mysql:5.6
    container_name: euconomista_db
    volumes:
      - mysqldbvolume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=euconomista
      - MYSQL_DATABASE=euconomista
      - MYSQL_USER=euconomista
      - MYSQL_PASSWORD=euconomista
    network_mode: euconomista

networks:
  euconomista:
    external: true

volumes:
  mysqldbvolume:
    driver: local