#!/bin/bash

DB_LOCAL='hmgestor'
DB_LOCAL_TEST='hmgestor_test'

ARQUIVO='backup.sql'
USER='root'
PASS='123'

echo -ne "Exportando base de dados '$DB_LOCAL' para '$ARQUIVO'...\n"
mysqldump -u$USER -p$PASS $DB_LOCAL > $ARQUIVO

echo -ne "Apagando e criando base de dados '$DB_LOCAL_TEST'...\n"
mysql -u$USER -p$PASS -e "DROP DATABASE IF EXISTS $DB_LOCAL_TEST; CREATE DATABASE $DB_LOCAL_TEST;"

echo -ne "Importando backup para '$DB_LOCAL_TEST'...\n"
mysql -u$USER -p$PASS $DB_LOCAL_TEST < $ARQUIVO

echo -ne "Apagando arquivo '$ARQUIVO'...\n"
rm $ARQUIVO

echo -ne "OK\n"